node {
 try  {
 notify('Job Started') 

 def project_path="devops/"
 
 dir(project_path) {
    
 
   stage('Docker-Stage-Deployment') {
   sh label: 'DOCKER DEPLOYMENT', script: 'docker-compose up -d --build'
  }
	 
 stage('Input for deploy in production server') {            
   input('Do you want to deploy into production server proceed?')
        }
 }
notify('Job Completed')   
} catch (err) {
  notify("Error ${err}")
  currentBuild.result = 'FAILURE'
}
}

def notify(status){
    emailext (
	to: "chakradhar1998@outlook.com",
	subject: "${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
	 body: """<p>${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
	<p>Check console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>""",
		)
	}
